--- 
- name: configure repository
  hosts: all
  vars:
    my_package: nmap
  tasks:

  - name: connect to example repo
    yum_repository:
      name: lab11
      description: lab 11 repo
      file: example.repo
      baseurl: http://control.example.com
      gpgcheck: yes

  - name: install package
    yum:
      name: "{{ my_package }}"
      state: present

  - name: get package facts
    package_facts:
      manager: auto

  - name: show package facts for {{ my_package }}
    debug:
      var: ansible_facts.packages[my_package]
    when: my_package in ansible_facts.packages

