--- 
- name: configure repository
  become: true
  hosts: ansible2
  vars:
    my_package: mariadb-server
  tasks:
  
  - name: get package facts
    package_facts:
      manager: auto

  - name: show package facts for {{ my_package }}
    debug:
      var: ansible_facts.packages[my_package]
    when: my_package in ansible_facts.packages

  - name: install package
    yum:
      name: "{{ my_package }}"
      state: present

  - name: get package facts
    package_facts:
      manager: auto

  - name: show package facts for {{ my_package }}
    debug:
      var: ansible_facts.packages[my_package]
    when: my_package in ansible_facts.packages

