---
#open port 21 for vsftpd in the security group
- name: install vsftpd
  hosts: ansible2 
  tasks:
  - name: get basic vsftpd operational
    yum:
      name: vsftpd
      state: installed
  - name: start and enable vsftpd
    service:
      name: vsftpd
      enabled: yes
      state: started
  - name: open port in firewall
    firewalld:
      service: ftp
      permanent: yes
      immediate: yes
      state: enabled

- name: configure VSFTPD using a template
  hosts: ansible2 
  vars:
    anonymous_enable: yes
    local_enable: yes
    write_enable: yes
    anon_upload_enable: yes
  tasks:
  - name: use template to copy FTP config
    template:
      src: vsftpd.j2
      dest: /etc/vsftpd/vsftpd.conf

- name: configure vsftpd permissions
  hosts: ansible2 
  tasks:
  - name: set permissions
    file:
      path: /var/ftp/pub
      mode: '0777'

    
