- name: simple block example
  hosts: all
  tasks:
    - name: setting up http
#block act as a super task    
      block:
      - name: installing http
        yum:
          name: httpd
          state: present
      - name: restart httpd
        service:
          name: httpd
          state: started
      when: ansible_distribution == "RedHat"
