---
- name: when demo
  hosts: all
  vars:
    supported_distros:
      - Redhat
      - CentOS
      - Fedora
 #if you have Amazon distribution task will be skipped 
  tasks:
    - name: install RH family specific packages
      yum:
        name: nginx
        state: present
      when: ansible_distribution in supported_distros 


