---
- name: database server is running
  hosts: lamp_prod
  vars:
    database_packages:
      - mariadb-server
      - python3-PyMySQL

  tasks: 
    - name: mariadb packages are installed
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ database_packages }}"
      when: ( ansible_distribution == "RedHat" and ansible_distribution_major_version == "9") or (ansible_distribution == "Amazon" and ansible_distribution_major_version == "2" )
    - name: start the db service
      service: 
        name: mariadb
        state: started
        enabled: true


