---
- name: create users using a loop testremote
  hosts: all
  tasks: 
  - name: create users 
    user: 
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
    loop:
      - name: joe
        groups: wheel
      - name: sara
        groups: users
      - name: mohamed
        groups: users

