---
- name: test register
  hosts: all
  tasks:
    - shell: cat /etc/passwd
      register: passwd_contents
    - debug: 
        msg: echo "passwd contains user rg"
      when: passwd_contents.stdout.find('rg') != -1
#ansible -m user -a "name=rg" ansible1