---
- name: show how debug works
  hosts: all
  vars:
    user: fahd
  tasks:
  - name: show value of a fact
    debug: 
      msg: this system has {{ ansible_facts['memfree_mb'] }} available ram
  - name: FIXME show a custom variable
    debug: 
      msg: Hello
      verbosity: 1
#(add -v as verbosity: 1 to trigger this task)      
